repos:
-   repo: local
    hooks:

    - id: black
      name: black
      description: "Black: The uncompromising Python code formatter"
      entry: black
      language: python
      require_serial: true
      types_or: [python, pyi]

    - id: ruff
      name: ruff
      description: "Ruff: The uncompromising Python code formatter"
      entry: ruff
      language: python
      types_or: [python, pyi]
      args: [ --fix, --exit-non-zero-on-fix ]

    - id: pytest-check
      name: pytest-check
      entry: pytest
      types: [python]
      language: python
      pass_filenames: false
      always_run: true

-   repo: https://github.com/pycqa/flake8
    rev: '6.0.0'
    hooks:
    -   id: flake8
